2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_setup.py:_flush():76] Configure stats pid to 22782
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_setup.py:_flush():76] Loading settings from /home/luungoc/.config/wandb/settings
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_setup.py:_flush():76] Loading settings from /home/luungoc/Continual Learning/Bert-Adapter/Adapter-BERT/src/wandb/settings
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_init.py:_log_setup():507] Logging user logs to /home/luungoc/Continual Learning/Bert-Adapter/Adapter-BERT/src/wandb/run-20231208_124732-d3ojs05g/logs/debug.log
2023-12-08 12:47:32,577 INFO    MainThread:22782 [wandb_init.py:_log_setup():508] Logging internal logs to /home/luungoc/Continual Learning/Bert-Adapter/Adapter-BERT/src/wandb/run-20231208_124732-d3ojs05g/logs/debug-internal.log
2023-12-08 12:47:32,578 INFO    MainThread:22782 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2e5410a550>
2023-12-08 12:47:32,578 INFO    MainThread:22782 [wandb_init.py:init():547] calling init triggers
2023-12-08 12:47:32,578 INFO    MainThread:22782 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-12-08 12:47:32,578 INFO    MainThread:22782 [wandb_init.py:init():596] starting backend
2023-12-08 12:47:32,579 INFO    MainThread:22782 [wandb_init.py:init():600] setting up manager
2023-12-08 12:47:32,595 INFO    MainThread:22782 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-08 12:47:32,596 INFO    MainThread:22782 [wandb_init.py:init():606] backend started and connected
2023-12-08 12:47:32,609 INFO    MainThread:22782 [wandb_run.py:_label_probe_notebook():1235] probe notebook
2023-12-08 12:47:32,610 INFO    MainThread:22782 [wandb_run.py:_label_probe_notebook():1245] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-08 12:47:32,610 INFO    MainThread:22782 [wandb_init.py:init():703] updated telemetry
2023-12-08 12:47:32,615 INFO    MainThread:22782 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-12-08 12:47:33,293 ERROR   MainThread:22782 [wandb_init.py:init():762] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-12-08 12:47:33,601 ERROR   MainThread:22782 [wandb_init.py:init():1170] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/home/luungoc/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/luungoc/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
